##Params file

#Give a name to your project!
network_name=corrNetTop2-400

#Testing null model (0=false, 1=true)
nullModel=0

## Section 1: File paths ##
##All files should be under the working directory or a sub-directory of the working directory

#Set path for input files and output files
working_directory=/path/to/project/

codingSeqFile=inputFiles/hg38_cds.fasta
utrSeqFile=inputFiles/hg38_3utr.fasta

networkRepositoryFile=inputFiles/network.tsv
proteinInfoMappingFile=inputFiles/mapping.tsv

## Section 2: Clustering measures

clusteringMeasure=4

bpScoreThreshold=4.0
rescaleThreshold=0.85

## Section 3: Monte Carlo Sampling ##

lowerBoundToSample=3
upperBoundToSample=2000

numberOfSamplings=100000
samplingMethod=1
